[package]
name = "orgish"
version = "0.1.0"
authors = [ "Sam Brew <arctic.hen@pm.me>" ]
edition = "2021"

[dependencies]
thiserror = "1"
uuid = { version = "1", features = [ "v4", "fast-rng" ], optional = true }
chrono = "^0.4.35"

[features]
default = [ "uuid-id-parser" ]
uuid-id-parser = [ "uuid" ]
